output_dir: "docs"
default_timezone: "America/New_York"

teams:
  - name: "Orcas"
    slug: "orcas-winter2026-6a"              
    league_name: "Winter 2026 Division 6A"
    api_url: "https://api.bondsports.co/v4/competitions/4fd5e832-5d86-400a-af3f-7a01c20d1e4e/stages/160/game-scores"
    my_team_ids: [1314]           
    my_team_names: ["Orcas"]  

  - name: "Alligator Skinners"
    slug: "alligator-skinners-winter-2026-d3"
    league_name: "Winter 2026 Division 3"
    api_url: "https://api.bondsports.co/v4/competitions/180251ce-9fbc-4153-b7f6-ce3530a2c7f9/stages/153/game-scores"
    my_team_ids: [1254]
    my_team_names: ["Alligator Skinners"]

  - name: "Grocery Sticks"
    slug: "grocery-sticks-winter-2026-d5a"
    league_name: "Winter 2026 Division 5A"
    api_url: "https://api.bondsports.co/v4/competitions/00d2c916-8370-463c-8d83-01c9ce2de443/stages/158/game-scores"
    my_team_ids: [1295]
    my_team_names: ["Grocery Sticks"]
